-- Q: What is the total amount spent by Homer Simpson across all credit card transactions?
-- A: To find this, we need to sum the transaction amounts for Homer Simpson from both credit card tables.
--    Here are the steps:
--    1. Identify Homer Simpson's transactions in the FBS_Viza_Costmo table
--    2. Identify Homer Simpson's transactions in the Planet_Express table
--    3. Sum the transaction amounts from both tables
--    4. Display the result